server:
  port: YOUR_PORT

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/YOUR_DB_NAME
      database: YOUR_DB_USERNAME

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:YOUR_PORT/eureka
  instance:
    hostname: localhost               # Force to register with localhost instead of mshome.net
    prefer-ip-address: true