server:
  port: YOUR_PORT

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/YOUR_DB_NAME
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:YOUR_PORT/eureka
  instance:
    hostname: localhost               # Force to register with localhost instead of mshome.net
    prefer-ip-address: true