server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/fitness_acitivities_db
      database: fitness_acitivities_db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost               # Force to register with localhost instead of mshome.net
    prefer-ip-address: true

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
